pub(super) struct DemoDecor {
            pub(super) name: &'static str,
            pub(super) file: &'static str,
            pub(super) pos: (f32, f32),
            pub(super) scale: f32,
            /// Cap (degrés autour de Y) : oriente le décor vers ce qu'il
            /// raconte (portes des cabanes vers la route, roue du moulin côté
            /// rivière…). Les glb sortent de Blender porte vers -Z.
            pub(super) yaw_deg: f32,
            pub(super) solide: bool,
            /// Clip joué en boucle (assets riggés de gen_nature_animated.py).
            pub(super) anim: Option<&'static str>,
        }
        // Landmarks posés à la main : le hameau (centre-est, sur la route), le
        // promontoire (tour + anneau de rochers), les ponts, les moulins et la
        // vie des berges. Le reste (forêt, lisières, fleurs, riz) est semé
        // procéduralement plus bas.
pub(super) const NATURE_DECOR: &[DemoDecor] = &[
            DemoDecor {
                name: "Pont 1",
                file: "nature_bridge.glb",
                pos: (-16.0, 14.0),
                scale: 1.15,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Pont 2",
                file: "nature_bridge.glb",
                pos: (-26.0, -10.0),
                scale: 1.15,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            // Hameau : deux cabanes porte vers la route (au sud d'elles, d'où
            // le cap 180°), la hutte de l'autre côté de la route, le puits, la
            // charrette, le torii qui marque l'entrée du chemin.
            DemoDecor {
                name: "Cabane 1",
                file: "nature_cabin.glb",
                pos: (6.0, 9.0),
                scale: 1.0,
                yaw_deg: 180.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Cabane 2",
                file: "nature_cabin.glb",
                pos: (14.0, 9.0),
                scale: 1.0,
                yaw_deg: 180.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Hutte",
                file: "nature_hut.glb",
                pos: (10.0, 21.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Puits",
                file: "nature_well.glb",
                pos: (10.0, 7.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Charrette",
                file: "nature_cart.glb",
                pos: (7.5, 11.5),
                scale: 1.0,
                yaw_deg: 35.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Torii",
                file: "nature_torii.glb",
                pos: (10.0, 12.2),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Tas de bois",
                file: "nature_woodpile.glb",
                pos: (4.5, 10.8),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Bannière",
                file: "nature_banner.glb",
                pos: (13.0, 4.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            // Encadrent l'entrée du torii, de part et d'autre du chemin.
            DemoDecor {
                name: "Lanterne 1",
                file: "nature_lantern.glb",
                pos: (5.0, 13.5),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Lanterne 2",
                file: "nature_lantern.glb",
                pos: (15.0, 13.5),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            // Clôtures des potagers, de part et d'autre des cabanes.
            DemoDecor {
                name: "Clôture 1",
                file: "nature_fence.glb",
                pos: (4.0, 6.2),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Clôture 2",
                file: "nature_fence.glb",
                pos: (16.0, 6.2),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Clôture 3",
                file: "nature_fence.glb",
                pos: (2.2, 8.2),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Clôture 4",
                file: "nature_fence.glb",
                pos: (18.5, 9.5),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: true,
                anim: None,
            },
            // Promontoire : la tour de guet au centre d'un anneau de rochers,
            // tous à ≥ 4 m de la tortue-canon (26, 13) qui y niche.
            DemoDecor {
                name: "Tour de guet",
                file: "nature_tower.glb",
                pos: (27.0, 9.0),
                scale: 1.1,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Rocher 1",
                file: "nature_rock.glb",
                pos: (31.2, 9.6),
                scale: 1.8,
                yaw_deg: 40.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Rocher 2",
                file: "nature_rock.glb",
                pos: (29.6, 4.8),
                scale: 1.5,
                yaw_deg: 130.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Rocher 3",
                file: "nature_rock.glb",
                pos: (24.0, 4.4),
                scale: 1.9,
                yaw_deg: 210.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Rocher 4",
                file: "nature_rock.glb",
                pos: (22.4, 8.8),
                scale: 1.4,
                yaw_deg: 300.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Rocher 5",
                file: "nature_rock.glb",
                pos: (30.4, 13.4),
                scale: 1.6,
                yaw_deg: 75.0,
                solide: true,
                anim: None,
            },
            // Moulins : la roue à aubes trempe dans la rivière sud (cap 180° —
            // la roue sort de Blender côté +X), les pales du moulin à vent
            // dominent les rizières.
            DemoDecor {
                name: "Moulin à eau",
                file: "nature_watermill.glb",
                pos: (-13.2, 17.0),
                scale: 1.0,
                yaw_deg: 180.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Moulin à vent",
                file: "nature_windmill.glb",
                pos: (10.0, 32.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            // Vie des berges et des champs (non solide sauf la barque).
            DemoDecor {
                name: "Feu de camp",
                file: "nature_campfire.glb",
                pos: (19.0, -6.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Épouvantail",
                file: "nature_scarecrow.glb",
                pos: (-8.0, 26.5),
                scale: 1.0,
                yaw_deg: 20.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Barque",
                file: "nature_boat.glb",
                pos: (-24.0, 11.8),
                scale: 1.0,
                yaw_deg: 20.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Panneau 1",
                file: "nature_signpost.glb",
                pos: (-12.8, 15.8),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Panneau 2",
                file: "nature_signpost.glb",
                pos: (11.6, 15.8),
                scale: 1.0,
                yaw_deg: 180.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Nénuphars 1",
                file: "nature_lily.glb",
                pos: (-21.0, 3.5),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Nénuphars 2",
                file: "nature_lily.glb",
                pos: (-16.5, 6.5),
                scale: 1.2,
                yaw_deg: 90.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Nénuphars 3",
                file: "nature_lily.glb",
                pos: (-23.5, 7.5),
                scale: 0.9,
                yaw_deg: 200.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Roseaux 1",
                file: "nature_reeds.glb",
                pos: (-12.4, 9.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Roseaux 2",
                file: "nature_reeds.glb",
                pos: (-25.2, 1.5),
                scale: 1.1,
                yaw_deg: 70.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Roseaux 3",
                file: "nature_reeds.glb",
                pos: (-13.6, 25.0),
                scale: 1.0,
                yaw_deg: 140.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Roseaux 4",
                file: "nature_reeds.glb",
                pos: (-18.7, 30.5),
                scale: 1.05,
                yaw_deg: 250.0,
                solide: false,
                anim: None,
            },
            // --- Faune ambiante (gen_menagerie_pack.py / gen_menagerie_pack2.py) : non
            //     solide sauf mention contraire (mouton/cerf, socle plein → sondes),
            //     `anim: Some("Idle")` sur toutes. Dispersée près de son biome (forêt,
            //     prairie, berges, hameau) — la non-solidité ne dispense pas du
            //     dégagement des spawns pour les 2 solides, cf. la doc de `DemoDecor`.
            DemoDecor {
                name: "Mouton",
                file: "fauna_sheep.glb",
                pos: (-3.0, 16.0),
                scale: 1.0,
                yaw_deg: 300.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Cerf",
                file: "fauna_deer.glb",
                pos: (4.5, -13.5),
                scale: 1.0,
                yaw_deg: 30.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Oiseau",
                file: "fauna_bird.glb",
                pos: (9.0, -12.0),
                scale: 1.0,
                yaw_deg: 80.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Papillon",
                file: "fauna_butterfly.glb",
                pos: (-2.0, 5.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Poisson",
                file: "fauna_fish.glb",
                pos: (-22.0, 5.0),
                scale: 1.0,
                yaw_deg: 45.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Luciole",
                file: "fauna_firefly.glb",
                pos: (-4.0, -2.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Lapin",
                file: "fauna_rabbit.glb",
                pos: (2.0, -6.0),
                scale: 1.0,
                yaw_deg: 60.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Grenouille",
                file: "fauna_frog.glb",
                pos: (-19.0, 5.5),
                scale: 1.0,
                yaw_deg: 170.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Poule",
                file: "fauna_chicken.glb",
                pos: (8.5, 12.0),
                scale: 1.0,
                yaw_deg: 200.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Écureuil",
                file: "fauna_squirrel.glb",
                pos: (14.0, -12.0),
                scale: 1.0,
                yaw_deg: 110.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Chouette",
                file: "fauna_owl.glb",
                pos: (12.0, -16.0),
                scale: 1.0,
                yaw_deg: 40.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Chauve-souris",
                file: "fauna_bat.glb",
                pos: (18.0, -12.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Escargot",
                file: "fauna_snail.glb",
                pos: (-14.5, 8.0),
                scale: 1.0,
                yaw_deg: 260.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Crabe",
                file: "fauna_crab.glb",
                pos: (-25.5, 10.5),
                scale: 1.0,
                yaw_deg: 15.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Canard",
                file: "fauna_duck.glb",
                pos: (-19.5, 8.5),
                scale: 1.0,
                yaw_deg: 220.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Hérisson",
                file: "fauna_hedgehog.glb",
                pos: (16.0, -18.0),
                scale: 1.0,
                yaw_deg: 330.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Abeille",
                file: "fauna_bee.glb",
                pos: (-3.5, -1.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Taupe",
                file: "fauna_mole.glb",
                pos: (0.0, -8.5),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            // --- Mécanismes de décor animés, 2 vagues (gen_menagerie_pack.py /
            //     gen_menagerie_pack2.py) : 3 clusters excentrés pour ne pas surcharger
            //     le hameau existant — steppe nord-centrale (caravane), champs à
            //     l'ouest des rizières (vie paysanne), rive est au sud du promontoire
            //     (quartier portuaire). Carillon/chaise/cerf-volant : hameau, non
            //     solides (trop fins pour les sondes, cf. gen_menagerie_pack.py).
            DemoDecor {
                name: "Girouette",
                file: "nature_weathervane.glb",
                pos: (-6.0, -16.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Pont-levis",
                file: "nature_drawbridge.glb",
                pos: (2.0, -20.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Catapulte",
                file: "nature_catapult.glb",
                pos: (-6.0, -24.0),
                scale: 1.0,
                yaw_deg: 30.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Clocheton",
                file: "nature_bell_tower.glb",
                pos: (3.0, -27.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Barrière de péage",
                file: "nature_toll_gate.glb",
                pos: (-2.0, -30.0),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Puits à manivelle",
                file: "nature_well_windlass.glb",
                pos: (-7.0, -30.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Marteau-pilon",
                file: "nature_forge_hammer.glb",
                pos: (-30.0, 22.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Métier à tisser",
                file: "nature_weaving_loom.glb",
                pos: (-24.0, 22.0),
                scale: 1.0,
                yaw_deg: 200.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Rouet",
                file: "nature_spinning_wheel.glb",
                pos: (-30.0, 27.0),
                scale: 1.0,
                yaw_deg: 250.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Soufflet",
                file: "nature_bellows.glb",
                pos: (-24.0, 27.0),
                scale: 1.0,
                yaw_deg: 150.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Pompe à eau",
                file: "nature_water_pump.glb",
                pos: (-18.0, 30.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Auvent de marché",
                file: "nature_market_awning.glb",
                pos: (-30.0, 32.0),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Moulin à prières",
                file: "nature_prayer_wheel.glb",
                pos: (-18.0, 24.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Bascule à balancier",
                file: "nature_seesaw.glb",
                pos: (-24.0, 32.0),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Manège",
                file: "nature_merry_go_round.glb",
                pos: (-33.0, 27.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Grue de quai",
                file: "nature_dock_crane.glb",
                pos: (30.0, 22.0),
                scale: 1.0,
                yaw_deg: 200.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Phare",
                file: "nature_lighthouse_lamp.glb",
                pos: (33.0, 27.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Horloge de tour",
                file: "nature_pendulum_clock.glb",
                pos: (30.0, 32.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Balançoire à corde",
                file: "nature_rope_swing.glb",
                pos: (16.0, -24.0),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: true,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Carillon à vent",
                file: "nature_wind_chime.glb",
                pos: (8.0, 20.5),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Chaise à bascule",
                file: "nature_rocking_chair.glb",
                pos: (11.5, 20.5),
                scale: 1.0,
                yaw_deg: 200.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Cerf-volant",
                file: "nature_kite.glb",
                pos: (0.0, 3.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            // Habillage des trois liaisons de voirie ajoutées aux aplats
            // (chemin des rizières, sentier du promontoire, place du hameau) :
            // pierres au carrefour route/chemin, pierre levée qui balise le
            // sentier est, panneaux aux embranchements, lanternes aux étapes.
            // Tout est posé en bord de voie, jamais sur la bande roulante.
            // IMPORTANT : dans NATURE_DECOR (pas MONSTER_DECOR) — seuls
            // NATURE_DECOR et VILLAGE_PROPS alimentent `solid_spots`, la
            // liste que le scatter procédural évite à ≥ 2,5 m.
            DemoDecor {
                name: "Pierre du carrefour 1",
                file: "nature_rock.glb",
                pos: (14.5, 17.6),
                scale: 0.45,
                yaw_deg: 25.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Pierre du carrefour 2",
                file: "nature_rock.glb",
                pos: (16.8, 19.2),
                scale: 0.3,
                yaw_deg: 130.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Pierre levée du sentier",
                file: "nature_rock.glb",
                // Bord sud du sentier, hors du rectangle de la forêt NE.
                pos: (30.0, -7.6),
                scale: 0.7,
                yaw_deg: 30.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Panneau des rizières",
                file: "nature_signpost.glb",
                pos: (-6.2, 15.8),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Panneau du promontoire",
                file: "nature_signpost.glb",
                pos: (7.0, -11.8),
                scale: 1.0,
                yaw_deg: 270.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Lanterne du carrefour",
                file: "nature_lantern.glb",
                pos: (8.4, 15.7),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Lanterne du sentier est",
                file: "nature_lantern.glb",
                pos: (24.0, -8.4),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            // --- Pack « pierre & mystique » (gen_stone_pack.py) : landmarks
            //     minéraux et sacrés qui étoffent les zones encore vides —
            //     landes de l'est, ruines du sud, clairières. Tous solides
            //     (TriMesh silhouette : on se faufile entre les pierres du
            //     cromlech ou sous l'arche), tous à ≥ 4 m des spawns. ---
            DemoDecor {
                name: "Menhir",
                file: "nature_menhir.glb",
                pos: (32.0, -2.0),
                scale: 1.0,
                yaw_deg: 30.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Cairn du sentier",
                file: "nature_cairn.glb",
                pos: (27.0, -8.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Cromlech",
                file: "nature_stone_circle.glb",
                pos: (33.0, 18.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            // Ruines du sud : l'arche et sa colonne racontent le domaine
            // disparu, entre le clocheton et la balançoire.
            DemoDecor {
                name: "Arche en ruine",
                file: "nature_ruin_arch.glb",
                pos: (7.0, -26.0),
                scale: 1.0,
                yaw_deg: 20.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Colonne brisée",
                file: "nature_ruin_column.glb",
                pos: (10.0, -28.0),
                scale: 1.0,
                yaw_deg: 70.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Cristaux",
                file: "nature_crystal_cluster.glb",
                pos: (18.0, -28.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            // Bord du chemin des rizières, tourné vers les marcheurs (est).
            DemoDecor {
                name: "Autel du chemin",
                file: "nature_shrine.glb",
                pos: (-7.5, 20.0),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Lanterne de pierre",
                file: "nature_stone_lantern.glb",
                pos: (17.8, 13.2),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Ruche",
                file: "nature_beehive.glb",
                pos: (19.5, 21.5),
                scale: 1.0,
                yaw_deg: 210.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Totem",
                file: "nature_totem.glb",
                pos: (-24.0, -18.0),
                scale: 1.0,
                yaw_deg: 150.0,
                solide: true,
                anim: None,
            },
            // Kiosque du hameau : l'entrée (face -Z du glb) regarde le chemin
            // au sud, l'intérieur reste traversable entre les poteaux.
            DemoDecor {
                name: "Kiosque",
                file: "nature_gazebo.glb",
                pos: (3.5, 19.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
        ];

        // Hameau fortifié : assets « maison », générés procéduralement par
        // scripts/blender/gen_hamlet_*.py (cf. sprintcration3delement.md et
        // la mémoire projet `charte-graphique-assets-maison` pour le détail
        // du pipeline). Remplace depuis le Sprint 7 les assets tiers
        // village_*.glb (Medieval Village Pack, Quaternius/CC0, retraités par
        // scripts/blender/import_village_pack.py) — mêmes noms de fonction/
        // silhouette, aucune géométrie tierce réutilisée. Posé dans le coin
        // sud-est de la carte (x∈[22,36], z∈[-36,-20]), à l'écart du hameau
        // existant et à ≥ 4 m du spawn le plus proche (créature 5, (20,-20))
        // — la règle des 3,5 m (RAY_DIST) ne s'applique qu'au décor solide,
        // testée plus bas.
pub(super) const VILLAGE_PROPS: &[DemoDecor] = &[
            // --- Bâtiments (grille 3×4, colonnes x=25/29/33, lignes
            //     z=-23/-27/-30.5/-34) ---
            DemoDecor {
                name: "Caserne du hameau",
                file: "hamlet_barracks.glb",
                pos: (25.0, -23.0),
                scale: 1.0,
                yaw_deg: 200.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Tour du hameau",
                file: "hamlet_bell_tower.glb",
                pos: (29.0, -23.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Auberge",
                file: "hamlet_inn.glb",
                pos: (33.0, -23.0),
                scale: 1.0,
                yaw_deg: 160.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Forge",
                file: "hamlet_blacksmith.glb",
                pos: (25.0, -27.0),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Puits du hameau",
                file: "hamlet_well.glb",
                pos: (29.0, -27.0),
                scale: 2.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Scierie",
                file: "hamlet_sawmill.glb",
                pos: (33.0, -27.0),
                scale: 1.0,
                yaw_deg: 270.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Maison du hameau 1",
                file: "hamlet_house_a.glb",
                pos: (25.0, -30.5),
                scale: 1.0,
                yaw_deg: 190.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Gazebo du hameau",
                file: "hamlet_gazebo.glb",
                pos: (29.0, -30.5),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Moulin du hameau",
                file: "hamlet_mill.glb",
                pos: (33.0, -30.5),
                scale: 1.0,
                yaw_deg: 250.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Maison du hameau 2",
                file: "hamlet_house_b.glb",
                pos: (25.0, -34.0),
                scale: 1.0,
                yaw_deg: 180.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Écurie",
                file: "hamlet_stable.glb",
                pos: (29.0, -34.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Maison du hameau 3",
                file: "hamlet_house_c.glb",
                pos: (33.0, -34.0),
                scale: 1.0,
                yaw_deg: 220.0,
                solide: true,
                anim: None,
            },
            // --- Étals et clôtures (solides) ---
            DemoDecor {
                name: "Étal du marché 1",
                file: "hamlet_market_stand_a.glb",
                pos: (27.0, -24.5),
                scale: 2.2,
                yaw_deg: 45.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Étal du marché 2",
                file: "hamlet_market_stand_b.glb",
                pos: (31.0, -24.5),
                scale: 2.2,
                yaw_deg: 315.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Clôture du hameau 1",
                file: "hamlet_fence.glb",
                pos: (26.0, -19.5),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Clôture du hameau 2",
                file: "hamlet_fence.glb",
                pos: (29.0, -19.5),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Clôture du hameau 3",
                file: "hamlet_fence.glb",
                pos: (32.0, -19.5),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Clôture du hameau 4",
                file: "hamlet_fence.glb",
                pos: (27.0, -35.5),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Clôture du hameau 5",
                file: "hamlet_fence.glb",
                pos: (31.0, -35.5),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            // --- Petit décor solide (tonneaux, caisses, bancs, rochers) ---
            DemoDecor {
                name: "Tonneau du hameau 1",
                file: "hamlet_barrel.glb",
                pos: (23.0, -24.0),
                scale: 3.0,
                yaw_deg: 15.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Tonneau du hameau 2",
                file: "hamlet_barrel.glb",
                pos: (34.7, -25.0),
                scale: 3.0,
                yaw_deg: 80.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Tonneau du hameau 3",
                file: "hamlet_barrel.glb",
                pos: (27.5, -21.5),
                scale: 3.0,
                yaw_deg: 200.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Caisse du hameau 1",
                file: "hamlet_crate.glb",
                pos: (23.0, -28.0),
                scale: 3.0,
                yaw_deg: 25.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Caisse du hameau 2",
                file: "hamlet_crate.glb",
                pos: (34.7, -29.0),
                scale: 3.0,
                yaw_deg: 140.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Caisse du hameau 3",
                file: "hamlet_crate.glb",
                pos: (30.5, -21.5),
                scale: 3.0,
                yaw_deg: 300.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Banc du hameau 1",
                file: "hamlet_bench_a.glb",
                pos: (27.0, -28.75),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Banc du hameau 2",
                file: "hamlet_bench_a.glb",
                pos: (31.0, -28.75),
                scale: 3.0,
                yaw_deg: 180.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Banc du hameau 3",
                file: "hamlet_bench_b.glb",
                pos: (27.0, -32.25),
                scale: 3.0,
                yaw_deg: 90.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Banc du hameau 4",
                file: "hamlet_bench_b.glb",
                pos: (31.0, -32.25),
                scale: 3.0,
                yaw_deg: 270.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Rocher du hameau 1",
                file: "hamlet_rocks.glb",
                pos: (23.0, -32.0),
                scale: 2.5,
                yaw_deg: 10.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Rocher du hameau 2",
                file: "hamlet_rocks.glb",
                pos: (34.7, -32.5),
                scale: 2.2,
                yaw_deg: 80.0,
                solide: true,
                anim: None,
            },
            DemoDecor {
                name: "Rocher du hameau 3",
                file: "hamlet_rocks.glb",
                pos: (24.0, -20.5),
                scale: 2.0,
                yaw_deg: 140.0,
                solide: true,
                anim: None,
            },
            // --- Décor traversable (sacs, foin, paquets, portes/fenêtres
            //     posées, fumée…) : aucune contrainte de dégagement. ---
            DemoDecor {
                name: "Sac du hameau 1",
                file: "hamlet_bag.glb",
                pos: (28.0, -24.0),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Sac du hameau 2",
                file: "hamlet_bag.glb",
                pos: (32.0, -31.0),
                scale: 3.0,
                yaw_deg: 90.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Sac ouvert du hameau",
                file: "hamlet_bag_open.glb",
                pos: (26.0, -24.5),
                scale: 3.0,
                yaw_deg: 45.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Sacs du hameau",
                file: "hamlet_bags.glb",
                pos: (34.0, -31.5),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Foin du hameau 1",
                file: "hamlet_hay.glb",
                pos: (24.0, -22.0),
                scale: 3.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Foin du hameau 2",
                file: "hamlet_hay.glb",
                pos: (34.0, -24.0),
                scale: 3.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Foin du hameau 3",
                file: "hamlet_hay.glb",
                pos: (28.0, -32.0),
                scale: 3.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Paquet du hameau 1",
                file: "hamlet_package_a.glb",
                pos: (30.0, -24.5),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Paquet du hameau 2",
                file: "hamlet_package_a.glb",
                pos: (24.0, -31.0),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Paquet du hameau 3",
                file: "hamlet_package_b.glb",
                pos: (32.0, -28.0),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Paquet du hameau 4",
                file: "hamlet_package_b.glb",
                pos: (26.0, -29.0),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Chaudron de la forge",
                file: "hamlet_cauldron.glb",
                pos: (24.5, -27.0),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Feu du hameau",
                file: "hamlet_bonfire.glb",
                pos: (28.0, -29.0),
                scale: 3.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Fumée de la forge",
                file: "hamlet_smoke.glb",
                pos: (24.5, -27.5),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Fumée de la scierie",
                file: "hamlet_smoke.glb",
                pos: (33.0, -27.3),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Lame de la scierie",
                file: "hamlet_sawmill_saw.glb",
                pos: (33.0, -27.6),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Porte ronde du hameau",
                file: "hamlet_door_round.glb",
                pos: (27.0, -22.5),
                scale: 2.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Porte droite du hameau",
                file: "hamlet_door_straight.glb",
                pos: (31.0, -23.5),
                scale: 2.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Fenêtre ronde 1",
                file: "hamlet_round_window.glb",
                pos: (24.3, -23.5),
                scale: 2.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Fenêtre ronde 2",
                file: "hamlet_round_window.glb",
                pos: (33.7, -31.0),
                scale: 2.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Fenêtre du hameau 1",
                file: "hamlet_window_a.glb",
                pos: (25.5, -26.0),
                scale: 2.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Fenêtre du hameau 2",
                file: "hamlet_window_a.glb",
                pos: (32.5, -31.5),
                scale: 2.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Fenêtre du hameau 3",
                file: "hamlet_window_b.glb",
                pos: (28.5, -31.0),
                scale: 2.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Fenêtre du hameau 4",
                file: "hamlet_window_b.glb",
                pos: (30.5, -27.0),
                scale: 2.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Cloche du hameau",
                file: "hamlet_bell.glb",
                pos: (29.0, -22.3),
                scale: 2.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Marches du hameau 1",
                file: "hamlet_stairs.glb",
                pos: (29.0, -21.7),
                scale: 2.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Marches du hameau 2",
                file: "hamlet_stairs.glb",
                pos: (33.0, -29.3),
                scale: 2.5,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Chemin du hameau 1",
                file: "hamlet_path_straight.glb",
                pos: (29.0, -21.0),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Chemin du hameau 2",
                file: "hamlet_path_straight.glb",
                pos: (29.0, -24.0),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Chemin du hameau 3",
                file: "hamlet_path_straight.glb",
                pos: (29.0, -27.0),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
            DemoDecor {
                name: "Chemin du hameau 4",
                file: "hamlet_path_straight.glb",
                pos: (29.0, -30.0),
                scale: 3.0,
                yaw_deg: 0.0,
                solide: false,
                anim: None,
            },
        ];

        // Ménagerie de monstres (Ultimate Monsters Bundle, Quaternius/CC0,
        // retraité par scripts/blender/import_monster_pack.py — armature/
        // skin retirés à l'export, ce ne sont que des silhouettes figées en
        // pose de repos). Non solides à dessein : ce pack est riggé dans le
        // fichier source, et `MAX_SKINNED_INSTANCES` (src/gfx/renderer.rs,
        // partagé avec les créatures MMORPG et le décor nature animé, déjà
        // ~66/96 utilisés) aurait explosé si ces 45 assets gardaient leur
        // squelette — cf. le script pour le détail. Posés en grille dans la
        // bande nord jusque-là vide (x∈[-16,16], z∈[-34,-20]), à l'écart de
        // toute zone déjà aménagée.
pub(super) const MONSTER_DECOR: &[DemoDecor] = &[
            DemoDecor {
                name: "Monstre Alien",
                file: "monster_alien.glb",
                pos: (-16.0, -34.0),
                scale: 1.0,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Alien 2",
                file: "monster_alien_b.glb",
                pos: (-12.0, -34.0),
                scale: 0.9,
                yaw_deg: 45.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Alpaking",
                file: "monster_alpaking.glb",
                pos: (-8.0, -34.0),
                scale: 0.9,
                yaw_deg: 90.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Alpaking évolué",
                file: "monster_alpaking_evolved.glb",
                pos: (-4.0, -34.0),
                scale: 0.9,
                yaw_deg: 135.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Armabee",
                file: "monster_armabee.glb",
                pos: (0.0, -34.0),
                scale: 0.9,
                yaw_deg: 180.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Armabee évolué",
                file: "monster_armabee_evolved.glb",
                pos: (4.0, -34.0),
                scale: 0.9,
                yaw_deg: 225.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Birb",
                file: "monster_birb.glb",
                pos: (8.0, -34.0),
                scale: 1.0,
                yaw_deg: 270.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Démon bleu",
                file: "monster_blue_demon.glb",
                pos: (12.0, -34.0),
                scale: 0.9,
                yaw_deg: 315.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Lapin monstre",
                file: "monster_bunny.glb",
                pos: (16.0, -34.0),
                scale: 0.9,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Cactoro",
                file: "monster_cactoro.glb",
                pos: (-16.0, -30.5),
                scale: 0.9,
                yaw_deg: 45.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Cactoro 2",
                file: "monster_cactoro_b.glb",
                pos: (-12.0, -30.5),
                scale: 0.9,
                yaw_deg: 90.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Chat monstre",
                file: "monster_cat.glb",
                pos: (-8.0, -30.5),
                scale: 1.3,
                yaw_deg: 135.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Poule monstre",
                file: "monster_chicken.glb",
                pos: (-4.0, -30.5),
                scale: 1.3,
                yaw_deg: 180.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Démon",
                file: "monster_demon.glb",
                pos: (0.0, -30.5),
                scale: 0.75,
                yaw_deg: 225.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Démon 2",
                file: "monster_demon_b.glb",
                pos: (4.0, -30.5),
                scale: 0.9,
                yaw_deg: 270.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Dino",
                file: "monster_dino.glb",
                pos: (8.0, -30.5),
                scale: 0.9,
                yaw_deg: 315.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Dragon",
                file: "monster_dragon.glb",
                pos: (12.0, -30.5),
                scale: 0.9,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Dragon évolué",
                file: "monster_dragon_evolved.glb",
                pos: (16.0, -30.5),
                scale: 0.75,
                yaw_deg: 45.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Poisson monstre",
                file: "monster_fish.glb",
                pos: (-16.0, -27.0),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Poisson monstre 2",
                file: "monster_fish_b.glb",
                pos: (-12.0, -27.0),
                scale: 0.9,
                yaw_deg: 135.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Grenouille monstre",
                file: "monster_frog.glb",
                pos: (-8.0, -27.0),
                scale: 0.9,
                yaw_deg: 180.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Fantôme",
                file: "monster_ghost.glb",
                pos: (-4.0, -27.0),
                scale: 0.75,
                yaw_deg: 225.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Crâne fantôme",
                file: "monster_ghost_skull.glb",
                pos: (0.0, -27.0),
                scale: 0.75,
                yaw_deg: 270.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Glub",
                file: "monster_glub.glb",
                pos: (4.0, -27.0),
                scale: 0.9,
                yaw_deg: 315.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Glub évolué",
                file: "monster_glub_evolved.glb",
                pos: (8.0, -27.0),
                scale: 0.9,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Goleling",
                file: "monster_goleling.glb",
                pos: (12.0, -27.0),
                scale: 0.9,
                yaw_deg: 45.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Goleling évolué",
                file: "monster_goleling_evolved.glb",
                pos: (16.0, -27.0),
                scale: 0.9,
                yaw_deg: 90.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Blob vert",
                file: "monster_green_blob.glb",
                pos: (-16.0, -23.5),
                scale: 1.3,
                yaw_deg: 135.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Blob épineux",
                file: "monster_green_spiky_blob.glb",
                pos: (-12.0, -23.5),
                scale: 0.9,
                yaw_deg: 180.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Hywirl",
                file: "monster_hywirl.glb",
                pos: (-8.0, -23.5),
                scale: 0.75,
                yaw_deg: 225.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Monkroose",
                file: "monster_monkroose.glb",
                pos: (-4.0, -23.5),
                scale: 0.9,
                yaw_deg: 270.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Mushnub",
                file: "monster_mushnub.glb",
                pos: (0.0, -23.5),
                scale: 1.0,
                yaw_deg: 315.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Mushnub évolué",
                file: "monster_mushnub_evolved.glb",
                pos: (4.0, -23.5),
                scale: 0.9,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Roi champignon",
                file: "monster_mushroom_king.glb",
                pos: (8.0, -23.5),
                scale: 0.9,
                yaw_deg: 45.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Ninja",
                file: "monster_ninja.glb",
                pos: (12.0, -23.5),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Ninja 2",
                file: "monster_ninja_b.glb",
                pos: (16.0, -23.5),
                scale: 0.9,
                yaw_deg: 135.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Orc",
                file: "monster_orc.glb",
                pos: (-16.0, -20.0),
                scale: 0.9,
                yaw_deg: 180.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Orc ennemi",
                file: "monster_orc_enemy.glb",
                pos: (-12.0, -20.0),
                scale: 1.0,
                yaw_deg: 225.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Pigeon monstre",
                file: "monster_pigeon.glb",
                pos: (-8.0, -20.0),
                scale: 1.3,
                yaw_deg: 270.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Blob rose",
                file: "monster_pink_blob.glb",
                pos: (-4.0, -20.0),
                scale: 1.3,
                yaw_deg: 315.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Squidle",
                file: "monster_squidle.glb",
                pos: (0.0, -20.0),
                scale: 0.75,
                yaw_deg: 0.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Tribal",
                file: "monster_tribal.glb",
                pos: (4.0, -20.0),
                scale: 0.75,
                yaw_deg: 45.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Sorcier",
                file: "monster_wizard.glb",
                pos: (8.0, -20.0),
                scale: 1.0,
                yaw_deg: 90.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Yeti",
                file: "monster_yeti.glb",
                pos: (12.0, -20.0),
                scale: 1.0,
                yaw_deg: 135.0,
                solide: false,
                anim: Some("Idle"),
            },
            DemoDecor {
                name: "Monstre Yeti 2",
                file: "monster_yeti_b.glb",
                pos: (16.0, -20.0),
                scale: 0.9,
                yaw_deg: 180.0,
                solide: false,
                anim: Some("Idle"),
            },
        ];
